### ISSUE TITLE
이건뭐에요?

### ISSUE THREAD

**Issue by Kerry-Cho** [BonexGoo/loveletter#1]
팬입니다.

**Comment by BonexGoo** [comment]
제 아들래미에게 소스코드 유산만 물려줄 것이 아니라
개발에 대한 아비의 철학도 알려주어야겠다는 생각이 들어
실천한 것입니다.

**Comment by Kerry-Cho** [comment]
답변 감사합니다.
항상 글재미있게 보고 있습니다^^

**Comment by BonexGoo** [comment]
감사합니다! ㅎㅎ
